services:
  backend:
    build:
      context: ./backend
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_TABLE: raawa-data
      AWS_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "9000:8000"
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local:latest
    user: root
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    ports:
      - "8002:8000"

volumes:
  dynamodb_data: